development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:2f2f24ec94940a273cbabcd420fa0301@scat.redistogo.com:11583/
  channel_prefix: chat_app_production
